import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="bg-gray-50">
      <body className="md:max-w-[375px] relative m-auto min-h-screen bg-white p-0 font-sans lining-nums text-gray-900 outline-none">
        {children}
      </body>
    </html>
  );
}
